// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWl35TL4v7QBRON0L_pAT-DJilIuN_W0',
    appId: '1:317286870569:web:e51241853488c8b08eb638',
    messagingSenderId: '317286870569',
    projectId: 'taskify-e8a61',
    authDomain: 'taskify-e8a61.firebaseapp.com',
    storageBucket: 'taskify-e8a61.appspot.com',
    measurementId: 'G-5SPEG72N35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTPHK5XKfYANDZwObGOeWuT0hC9oMq10',
    appId: '1:317286870569:android:ee707a34b41d373d8eb638',
    messagingSenderId: '317286870569',
    projectId: 'taskify-e8a61',
    storageBucket: 'taskify-e8a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rhnMGyWjmIM4Y4dojDr2Urx9vsuS4II',
    appId: '1:317286870569:ios:be7980894c61658d8eb638',
    messagingSenderId: '317286870569',
    projectId: 'taskify-e8a61',
    storageBucket: 'taskify-e8a61.appspot.com',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rhnMGyWjmIM4Y4dojDr2Urx9vsuS4II',
    appId: '1:317286870569:ios:d0fae6de3c0ba7358eb638',
    messagingSenderId: '317286870569',
    projectId: 'taskify-e8a61',
    storageBucket: 'taskify-e8a61.appspot.com',
    iosBundleId: 'com.example.taskify.RunnerTests',
  );
}
